---

additional_system_packages:
  - cups
  - cups-bsd
  - cups-client

# PLONE
plone_instance_name: senaite
plone_site_id: senaite
plone_zodb_cache_size: 50000
plone_timezone: "Africa/Gaborone"
plone_always_run_buildout: yes
plone_additional_eggs:
  - bhp.lims

plone_sources:
  - "bhp.lims = git github-bhp-lims:bhp-lims/bhp.lims.git"
  - "senaite.api = git https://github.com/senaite/senaite.api.git"
  - "senaite.core = git https://github.com/senaite/senaite.core.git"
  - "senaite.core.listing = git https://github.com/senaite/senaite.core.listing.git"
  - "senaite.core.supermodel = git https://github.com/senaite/senaite.core.supermodel.git"
  - "senaite.impress = git https://github.com/senaite/senaite.impress.git"
  - "senaite.jsonapi = git https://github.com/senaite/senaite.jsonapi.git"
  - "senaite.lims = git https://github.com/senaite/senaite.lims.git"
  - "senaite.storage = git https://github.com/senaite/senaite.storage.git"


# SECURITY
firewall_open_tcp_ports: [25, 80, 443]

# NGINX
nginx_keepalive_timeout: "300"
