---

# Run with ansible-playbook -i hosts.cfg playbook.yml
- hosts: senaite-xenial
  become: yes
  become_method: sudo
  gather_facts: yes
  pre_tasks:
    - include: senaite.ansible-playbook/senaite_pre_tasks.yml
    - name: Include credentials defined in `credentials.yml`
      include_vars: credentials.yml
      tags:
        - always
    - name: Include variables defined in `configure.yml`
      include_vars: configure.yml
      tags:
        - always

  tasks:
    - include: custom_pre.yml
    - include: senaite.ansible-playbook/senaite_base.yml
    - include: senaite.ansible-playbook/senaite_plone.yml
    - include: senaite.ansible-playbook/senaite_haproxy.yml
    - include: senaite.ansible-playbook/senaite_nginx.yml
    - include: senaite.ansible-playbook/senaite_munin.yml
    - include: senaite.ansible-playbook/senaite_postfix.yml
    - include: senaite.ansible-playbook/senaite_security.yml
    - include: custom_post.yml

  handlers:
    - include: senaite.ansible-playbook/senaite_handlers.yml
